import os
import re
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import Response
from sqlalchemy.orm import Session

from pyxie_core.audit import write_audit_event
from pyxie_core.models import Cluster, Node, Workload
from pyxie_core.reports import REPORTS, Scope, last_collection, parse_uuid_list

from .. import config
from ..auth_deps import get_current_user, require_admin
from ..deps import get_db
from ..report_export import to_csv, to_csv_zip, to_xlsx

router = APIRouter(prefix="/api/reports", tags=["reports"], dependencies=[Depends(get_current_user)])


def _scope(cluster_id: str | None, node_id: str | None, workload_id: str | None) -> Scope:
    try:
        return Scope(parse_uuid_list(cluster_id), parse_uuid_list(node_id), parse_uuid_list(workload_id))
    except ValueError:
        raise HTTPException(422, "cluster_id / node_id / workload_id must be comma-separated UUIDs")


def _jsonable(v):
    return v.isoformat() if isinstance(v, datetime) else v


def _col_out(c):
    return {"key": c.key, "label": c.label, "kind": c.kind, "hidden": c.hidden}


@router.get("/catalog")
def catalog():
    return [
        {"key": r.key, "label": r.label, "description": r.description, "columns": [_col_out(c) for c in r.columns]}
        for r in REPORTS.values()
    ]


@router.get("/status")
def status(db: Session = Depends(get_db)):
    return last_collection(db)


@router.get("/options")
def options(db: Session = Depends(get_db)):
    """Light lists for the scope pickers (clusters / hosts / guests)."""
    clusters = db.query(Cluster).filter(Cluster.is_missing.is_(False)).order_by(Cluster.name).all()
    nodes = db.query(Node).filter(Node.is_missing.is_(False)).order_by(Node.name).all()
    workloads = db.query(Workload).filter(Workload.is_missing.is_(False)).order_by(Workload.name).all()
    return {
        "clusters": [{"id": str(c.id), "name": c.name} for c in clusters],
        "nodes": [{"id": str(n.id), "name": n.name, "cluster_id": str(n.cluster_id)} for n in nodes],
        "workloads": [
            {
                "id": str(w.id),
                "name": w.name or f"vmid {w.vmid}",
                "vmid": w.vmid,
                "type": w.type,
                "node_id": str(w.node_id),
                "cluster_id": str(w.cluster_id),
            }
            for w in workloads
        ],
    }


@router.post("/refresh", dependencies=[Depends(require_admin)])
def refresh(db: Session = Depends(get_db), user=Depends(get_current_user)):
    """Re-collects disks/NICs/snapshots/IPs now instead of waiting for the
    next scheduled pass. Runs on the worker; poll /status for progress."""
    if last_collection(db)["running"]:
        raise HTTPException(409, "A collection is already running")
    import redis
    from rq import Queue

    conn = redis.from_url(os.environ["REDIS_URL"])
    Queue("analysis", connection=conn).enqueue("worker.jobs.collect_reporting_job", user.email, job_timeout=1800)
    write_audit_event(db, event_category="report", event_type="report.refresh_requested", actor=user.email, actor_type="user")
    return {"queued": True}


def _resolve(keys: list[str]):
    out = []
    for k in keys:
        if k not in REPORTS:
            raise HTTPException(404, f"Unknown report {k!r}")
        out.append(REPORTS[k])
    return out


@router.get("/export")
def export(
    reports: str = Query(..., description="comma-separated report keys, e.g. vInfo,vHost"),
    format: str = Query("xlsx", pattern="^(xlsx|csv)$"),
    cluster_id: str | None = None,
    node_id: str | None = None,
    workload_id: str | None = None,
    db: Session = Depends(get_db),
    user=Depends(get_current_user),
):
    selected = _resolve([k.strip() for k in reports.split(",") if k.strip()])
    if not selected:
        raise HTTPException(422, "No reports selected")
    scope = _scope(cluster_id, node_id, workload_id)
    built = [(r, r.build(db, scope)) for r in selected]
    now = datetime.now(timezone.utc)
    stamp = now.strftime("%Y-%m-%d_%H%M")
    coll = last_collection(db)
    if format == "xlsx":
        info = [
            ("Generated by", f"PyXie Manager {config.settings.APP_VERSION}"),
            ("Generated (UTC)", now.strftime("%Y-%m-%d %H:%M:%S")),
            ("Requested by", user.email),
            ("Scope", scope.describe(db)),
            ("Detail data collected (UTC)", (coll["collected_at"] or "never")),
            *[(f"Rows — {r.label}", str(len(rows))) for r, rows in built],
        ]
        body, media = to_xlsx(built, info), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        name = f"PyXie_{'_'.join(r.key for r, _ in built) if len(built) < 6 else 'All'}_{stamp}.xlsx"
    elif len(built) == 1:
        body, media = to_csv(*built[0]), "text/csv"
        name = f"PyXie_{built[0][0].key}_{stamp}.csv"
    else:
        body, media = to_csv_zip(built, stamp), "application/zip"
        name = f"PyXie_CSV_{stamp}.zip"
    write_audit_event(
        db,
        event_category="report",
        event_type="report.exported",
        actor=user.email,
        actor_type="user",
        metadata={"reports": [r.key for r, _ in built], "format": format, "scope": scope.describe(db), "rows": sum(len(x) for _, x in built)},
    )
    safe = re.sub(r"[^A-Za-z0-9._-]", "_", name)
    return Response(content=body, media_type=media, headers={"Content-Disposition": f'attachment; filename="{safe}"'})


@router.get("/{key}")
def report(
    key: str,
    cluster_id: str | None = None,
    node_id: str | None = None,
    workload_id: str | None = None,
    db: Session = Depends(get_db),
):
    (r,) = _resolve([key])
    rows = r.build(db, _scope(cluster_id, node_id, workload_id))
    return {
        "key": r.key,
        "label": r.label,
        "columns": [_col_out(c) for c in r.columns],
        "rows": [{**{k: _jsonable(v) for k, v in row.items()}, "id": str(i)} for i, row in enumerate(rows)],
        "collected_at": last_collection(db)["collected_at"],
    }
